version: '3.8'
services:

  fastapi:
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: fastapi
    ports:
     - "8081:8081"
    volumes:
      - "D://cityStream//data//realistic_traffic_data.json:/code/data/realistic_traffic_data.json"
    networks:
      - citystream-network
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    command: ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8081"]

  kafkaproducer:
    build:
      context: ./kafkaproducer
      dockerfile: dockerfile
    container_name: kafkaproducer
    networks:
      - citystream-network
    depends_on:
      - fastapi
      - kafka1
      - kafka2
      - kafka3

  kafkaconsumer:
    build:
      context: ./kafkaconsumer
      dockerfile: dockerfile
    container_name: kafkaconsumer
    env_file:
      - kafkaconsumer/.env
    networks:
      - citystream-network
    depends_on:
      - kafka1
      - kafka2
      - kafka3


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - citystream-network

  kafka1:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200
    ports:
      - "9092:9092"
    networks:
      - citystream-network
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_INTERNAL://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093,PLAINTEXT_INTERNAL://kafka2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200
    ports:
      - "9093:9093"
    networks:
      - citystream-network
    depends_on:
      - zookeeper

  kafka3:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,PLAINTEXT_INTERNAL://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094,PLAINTEXT_INTERNAL://kafka3:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200
    ports:
      - "9094:9094"
    networks:
      - citystream-network
    depends_on:
      - zookeeper

networks:
  citystream-network:
    driver: bridge
